apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: my-app
spec:
  serviceAccountName: my-app-sa
  containers:
    - name: nginx-container
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80