apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-app
  template:
    metadata:
      labels:
        app: pv-app
    spec:
      containers:
        - name: my-container
          image: nginx
          volumeMounts:
            - mountPath: "/usr/share/nginx/html" # The path inside the container
              name: my-storage # A reference to the volume definition below
      volumes:
        - name: my-storage # The name for the volume
          persistentVolumeClaim:
            claimName: my-app-pvc # This must match the name of the PVC