apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-label
  template:
    metadata:
      labels:
        app: nginx-label
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests: # minimum amount of resources a container is guaranteed to get.
              memory: "64Mi"
              cpu: "250m"
            limits: # the maximum amount of resources a container is allowed to use
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

