apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-processing-job
spec:
  completions: 10 # The Job is complete when 10 Pods have successfully finished.
  parallelism: 2  # Run 2 Pods at the same time.
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "echo 'Processing item...' && sleep 30 && echo 'Done!'"]
      restartPolicy: OnFailure